// ═══════════════════════════════════════════════════════════════
// F&O INSTRUMENT LIST  (from fo_mktlots.csv)
// Indices pinned at top, stocks alphabetically sorted
// ═══════════════════════════════════════════════════════════════
const FO_LIST = [
  // ── Indices ───────────────────────────────────────────────
  { name: "NIFTY 50", symbol: "NIFTY", lot: "65", type: "index" },
  { name: "NIFTY BANK", symbol: "BANKNIFTY", lot: "30", type: "index" },
  { name: "NIFTY FIN SERVICES", symbol: "FINNIFTY", lot: "60", type: "index" },
  { name: "NIFTY MID SELECT", symbol: "MIDCPNIFTY", lot: "120", type: "index" },
  { name: "NIFTY NEXT 50", symbol: "NIFTYNXT50", lot: "25", type: "index" },
  // ── Stocks (A-Z) ──────────────────────────────────────────
  { name: "360 ONE WAM", symbol: "360ONE", lot: "500", type: "stock" },
  { name: "ABB INDIA", symbol: "ABB", lot: "125", type: "stock" },
  { name: "ADANI ENERGY SOL", symbol: "ADANIENSOL", lot: "675", type: "stock" },
  { name: "ADANI ENTERPRISES", symbol: "ADANIENT", lot: "309", type: "stock" },
  {
    name: "ADANI GREEN ENERGY",
    symbol: "ADANIGREEN",
    lot: "600",
    type: "stock",
  },
  {
    name: "ADANI PORTS & SEZ",
    symbol: "ADANIPORTS",
    lot: "475",
    type: "stock",
  },
  { name: "ADITYA BIRLA CAP", symbol: "ABCAPITAL", lot: "3100", type: "stock" },
  { name: "ALKEM LABS", symbol: "ALKEM", lot: "125", type: "stock" },
  { name: "AMBER ENTERPRISES", symbol: "AMBER", lot: "100", type: "stock" },
  { name: "AMBUJA CEMENTS", symbol: "AMBUJACEM", lot: "1050", type: "stock" },
  { name: "ANGEL ONE", symbol: "ANGELONE", lot: "2500", type: "stock" },
  { name: "APL APOLLO TUBES", symbol: "APLAPOLLO", lot: "350", type: "stock" },
  { name: "APOLLO HOSPITALS", symbol: "APOLLOHOSP", lot: "125", type: "stock" },
  { name: "ASHOK LEYLAND", symbol: "ASHOKLEY", lot: "5000", type: "stock" },
  { name: "ASIAN PAINTS", symbol: "ASIANPAINT", lot: "250", type: "stock" },
  { name: "ASTRAL", symbol: "ASTRAL", lot: "425", type: "stock" },
  { name: "AU SMALL FIN BANK", symbol: "AUBANK", lot: "1000", type: "stock" },
  { name: "AUROBINDO PHARMA", symbol: "AUROPHARMA", lot: "550", type: "stock" },
  { name: "AVENUE SUPERMARTS", symbol: "DMART", lot: "150", type: "stock" },
  { name: "AXIS BANK", symbol: "AXISBANK", lot: "625", type: "stock" },
  { name: "BAJAJ AUTO", symbol: "BAJAJ-AUTO", lot: "75", type: "stock" },
  { name: "BAJAJ FINANCE", symbol: "BAJFINANCE", lot: "750", type: "stock" },
  { name: "BAJAJ FINSERV", symbol: "BAJAJFINSV", lot: "250", type: "stock" },
  { name: "BAJAJ HOLDINGS", symbol: "BAJAJHLDNG", lot: "50", type: "stock" },
  { name: "BANDHAN BANK", symbol: "BANDHANBNK", lot: "3600", type: "stock" },
  { name: "BANK OF BARODA", symbol: "BANKBARODA", lot: "2925", type: "stock" },
  { name: "BANK OF INDIA", symbol: "BANKINDIA", lot: "5200", type: "stock" },
  { name: "BHARAT DYNAMICS", symbol: "BDL", lot: "350", type: "stock" },
  { name: "BHARAT ELECTRONICS", symbol: "BEL", lot: "1425", type: "stock" },
  { name: "BHARAT FORGE", symbol: "BHARATFORG", lot: "500", type: "stock" },
  { name: "BHARAT PETROLEUM", symbol: "BPCL", lot: "1975", type: "stock" },
  { name: "BHARTI AIRTEL", symbol: "BHARTIARTL", lot: "475", type: "stock" },
  { name: "BHEL", symbol: "BHEL", lot: "2625", type: "stock" },
  { name: "BIOCON", symbol: "BIOCON", lot: "2500", type: "stock" },
  { name: "BLUE STAR", symbol: "BLUESTARCO", lot: "325", type: "stock" },
  { name: "BOSCH", symbol: "BOSCHLTD", lot: "25", type: "stock" },
  { name: "BRITANNIA", symbol: "BRITANNIA", lot: "125", type: "stock" },
  { name: "BSE", symbol: "BSE", lot: "375", type: "stock" },
  { name: "CANARA BANK", symbol: "CANBK", lot: "6750", type: "stock" },
  { name: "CDSL", symbol: "CDSL", lot: "475", type: "stock" },
  { name: "CG POWER", symbol: "CGPOWER", lot: "850", type: "stock" },
  { name: "CHOLAMANDALAM FIN", symbol: "CHOLAFIN", lot: "625", type: "stock" },
  { name: "CIPLA", symbol: "CIPLA", lot: "375", type: "stock" },
  { name: "COAL INDIA", symbol: "COALINDIA", lot: "1350", type: "stock" },
  { name: "COFORGE", symbol: "COFORGE", lot: "375", type: "stock" },
  { name: "COLGATE PALMOLIVE", symbol: "COLPAL", lot: "225", type: "stock" },
  { name: "COMPUTER AGE MGMT", symbol: "CAMS", lot: "750", type: "stock" },
  { name: "CONTAINER CORP", symbol: "CONCOR", lot: "1250", type: "stock" },
  { name: "CROMPTON GREAVES", symbol: "CROMPTON", lot: "1800", type: "stock" },
  { name: "CUMMINS INDIA", symbol: "CUMMINSIND", lot: "200", type: "stock" },
  { name: "DABUR INDIA", symbol: "DABUR", lot: "1250", type: "stock" },
  { name: "DALMIA BHARAT", symbol: "DALBHARAT", lot: "325", type: "stock" },
  { name: "DELHIVERY", symbol: "DELHIVERY", lot: "2075", type: "stock" },
  { name: "DIVI'S LABS", symbol: "DIVISLAB", lot: "100", type: "stock" },
  { name: "DIXON TECHNOLOGIES", symbol: "DIXON", lot: "50", type: "stock" },
  { name: "DLF", symbol: "DLF", lot: "825", type: "stock" },
  { name: "DR REDDY'S LABS", symbol: "DRREDDY", lot: "625", type: "stock" },
  { name: "EICHER MOTORS", symbol: "EICHERMOT", lot: "100", type: "stock" },
  { name: "ETERNAL (ZOMATO)", symbol: "ETERNAL", lot: "2425", type: "stock" },
  { name: "EXIDE INDUSTRIES", symbol: "EXIDEIND", lot: "1800", type: "stock" },
  { name: "FEDERAL BANK", symbol: "FEDERALBNK", lot: "5000", type: "stock" },
  { name: "FORTIS HEALTHCARE", symbol: "FORTIS", lot: "775", type: "stock" },
  { name: "FSN / NYKAA", symbol: "NYKAA", lot: "3125", type: "stock" },
  { name: "GAIL INDIA", symbol: "GAIL", lot: "3150", type: "stock" },
  { name: "GLENMARK PHARMA", symbol: "GLENMARK", lot: "375", type: "stock" },
  { name: "GMR AIRPORTS", symbol: "GMRAIRPORT", lot: "6975", type: "stock" },
  { name: "GODREJ CONSUMER", symbol: "GODREJCP", lot: "500", type: "stock" },
  {
    name: "GODREJ PROPERTIES",
    symbol: "GODREJPROP",
    lot: "275",
    type: "stock",
  },
  { name: "GRASIM INDUSTRIES", symbol: "GRASIM", lot: "250", type: "stock" },
  { name: "HAVELLS INDIA", symbol: "HAVELLS", lot: "500", type: "stock" },
  { name: "HCL TECHNOLOGIES", symbol: "HCLTECH", lot: "350", type: "stock" },
  { name: "HDFC AMC", symbol: "HDFCAMC", lot: "300", type: "stock" },
  { name: "HDFC BANK", symbol: "HDFCBANK", lot: "550", type: "stock" },
  { name: "HDFC LIFE", symbol: "HDFCLIFE", lot: "1100", type: "stock" },
  { name: "HERO MOTOCORP", symbol: "HEROMOTOCO", lot: "150", type: "stock" },
  { name: "HINDALCO", symbol: "HINDALCO", lot: "700", type: "stock" },
  { name: "HINDUSTAN AERONAUT", symbol: "HAL", lot: "150", type: "stock" },
  {
    name: "HINDUSTAN PETROLEUM",
    symbol: "HINDPETRO",
    lot: "2025",
    type: "stock",
  },
  {
    name: "HINDUSTAN UNILEVER",
    symbol: "HINDUNILVR",
    lot: "300",
    type: "stock",
  },
  { name: "HINDUSTAN ZINC", symbol: "HINDZINC", lot: "1225", type: "stock" },
  {
    name: "HITACHI ENERGY IND",
    symbol: "POWERINDIA",
    lot: "50",
    type: "stock",
  },
  { name: "HUDCO", symbol: "HUDCO", lot: "2775", type: "stock" },
  { name: "ICICI BANK", symbol: "ICICIBANK", lot: "700", type: "stock" },
  { name: "ICICI LOMBARD GIC", symbol: "ICICIGI", lot: "325", type: "stock" },
  { name: "ICICI PRU LIFE", symbol: "ICICIPRULI", lot: "925", type: "stock" },
  { name: "IDFC FIRST BANK", symbol: "IDFCFIRSTB", lot: "9275", type: "stock" },
  { name: "INDIAN BANK", symbol: "INDIANB", lot: "1000", type: "stock" },
  { name: "INDIAN ENERGY EXCH", symbol: "IEX", lot: "3750", type: "stock" },
  { name: "INDIAN OIL CORP", symbol: "IOC", lot: "4875", type: "stock" },
  { name: "IRFC", symbol: "IRFC", lot: "4250", type: "stock" },
  { name: "IREDA", symbol: "IREDA", lot: "3450", type: "stock" },
  { name: "INDUS TOWERS", symbol: "INDUSTOWER", lot: "1700", type: "stock" },
  { name: "INDUSIND BANK", symbol: "INDUSINDBK", lot: "700", type: "stock" },
  { name: "INFO EDGE / NAUKRI", symbol: "NAUKRI", lot: "375", type: "stock" },
  { name: "INFOSYS", symbol: "INFY", lot: "400", type: "stock" },
  { name: "INOX WIND", symbol: "INOXWIND", lot: "3575", type: "stock" },
  { name: "INDIGO (INTERGLOBE)", symbol: "INDIGO", lot: "150", type: "stock" },
  { name: "ITC", symbol: "ITC", lot: "1600", type: "stock" },
  { name: "JINDAL STEEL", symbol: "JINDALSTEL", lot: "625", type: "stock" },
  { name: "JIO FIN SERVICES", symbol: "JIOFIN", lot: "2350", type: "stock" },
  { name: "JSW ENERGY", symbol: "JSWENERGY", lot: "1000", type: "stock" },
  { name: "JSW STEEL", symbol: "JSWSTEEL", lot: "675", type: "stock" },
  {
    name: "JUBILANT FOODWORKS",
    symbol: "JUBLFOOD",
    lot: "1250",
    type: "stock",
  },
  {
    name: "KALYAN JEWELLERS",
    symbol: "KALYANKJIL",
    lot: "1175",
    type: "stock",
  },
  { name: "KAYNES TECHNOLOGY", symbol: "KAYNES", lot: "100", type: "stock" },
  { name: "KEI INDUSTRIES", symbol: "KEI", lot: "175", type: "stock" },
  { name: "KFIN TECHNOLOGIES", symbol: "KFINTECH", lot: "500", type: "stock" },
  {
    name: "KOTAK MAHINDRA BANK",
    symbol: "KOTAKBANK",
    lot: "2000",
    type: "stock",
  },
  { name: "KPIT TECHNOLOGIES", symbol: "KPITTECH", lot: "425", type: "stock" },
  { name: "L&T FINANCE", symbol: "LTF", lot: "2250", type: "stock" },
  { name: "LARSEN & TOUBRO", symbol: "LT", lot: "175", type: "stock" },
  { name: "LAURUS LABS", symbol: "LAURUSLABS", lot: "850", type: "stock" },
  { name: "LIC HOUSING FIN", symbol: "LICHSGFIN", lot: "1000", type: "stock" },
  { name: "LIC OF INDIA", symbol: "LICI", lot: "700", type: "stock" },
  { name: "LODHA DEVELOPERS", symbol: "LODHA", lot: "450", type: "stock" },
  { name: "LTIMINDTREE", symbol: "LTM", lot: "150", type: "stock" },
  { name: "LUPIN", symbol: "LUPIN", lot: "425", type: "stock" },
  { name: "MAHINDRA & MAHINDRA", symbol: "M&M", lot: "200", type: "stock" },
  {
    name: "MANAPPURAM FINANCE",
    symbol: "MANAPPURAM",
    lot: "3000",
    type: "stock",
  },
  { name: "MANKIND PHARMA", symbol: "MANKIND", lot: "225", type: "stock" },
  { name: "MARICO", symbol: "MARICO", lot: "1200", type: "stock" },
  { name: "MARUTI SUZUKI", symbol: "MARUTI", lot: "50", type: "stock" },
  { name: "MAX FINANCIAL", symbol: "MFSL", lot: "400", type: "stock" },
  { name: "MAX HEALTHCARE", symbol: "MAXHEALTH", lot: "525", type: "stock" },
  { name: "MAZAGON DOCK", symbol: "MAZDOCK", lot: "200", type: "stock" },
  { name: "MPHASIS", symbol: "MPHASIS", lot: "275", type: "stock" },
  { name: "MCX", symbol: "MCX", lot: "625", type: "stock" },
  { name: "MUTHOOT FINANCE", symbol: "MUTHOOTFIN", lot: "275", type: "stock" },
  {
    name: "NATIONAL ALUMINIUM",
    symbol: "NATIONALUM",
    lot: "3750",
    type: "stock",
  },
  { name: "NBCC INDIA", symbol: "NBCC", lot: "6500", type: "stock" },
  { name: "NESTLE INDIA", symbol: "NESTLEIND", lot: "500", type: "stock" },
  { name: "NHPC", symbol: "NHPC", lot: "6400", type: "stock" },
  { name: "NMDC", symbol: "NMDC", lot: "6750", type: "stock" },
  { name: "NTPC", symbol: "NTPC", lot: "1500", type: "stock" },
  { name: "NUVAMA WEALTH", symbol: "NUVAMA", lot: "500", type: "stock" },
  { name: "OBEROI REALTY", symbol: "OBEROIRLTY", lot: "350", type: "stock" },
  { name: "ONGC", symbol: "ONGC", lot: "2250", type: "stock" },
  { name: "OIL INDIA", symbol: "OIL", lot: "1400", type: "stock" },
  { name: "PAYTM", symbol: "PAYTM", lot: "725", type: "stock" },
  { name: "ORACLE FIN SERVICES", symbol: "OFSS", lot: "75", type: "stock" },
  { name: "PAGE INDUSTRIES", symbol: "PAGEIND", lot: "15", type: "stock" },
  { name: "PATANJALI FOODS", symbol: "PATANJALI", lot: "900", type: "stock" },
  {
    name: "PB FINTECH (PolicyBazaar)",
    symbol: "POLICYBZR",
    lot: "350",
    type: "stock",
  },
  {
    name: "PERSISTENT SYSTEMS",
    symbol: "PERSISTENT",
    lot: "100",
    type: "stock",
  },
  { name: "PETRONET LNG", symbol: "PETRONET", lot: "1900", type: "stock" },
  { name: "PG ELECTROPLAST", symbol: "PGEL", lot: "950", type: "stock" },
  { name: "PI INDUSTRIES", symbol: "PIIND", lot: "175", type: "stock" },
  {
    name: "PIDILITE INDUSTRIES",
    symbol: "PIDILITIND",
    lot: "500",
    type: "stock",
  },
  { name: "PIRAMAL PHARMA", symbol: "PPLPHARMA", lot: "2625", type: "stock" },
  { name: "PNB HOUSING FIN", symbol: "PNBHOUSING", lot: "650", type: "stock" },
  { name: "POLYCAB INDIA", symbol: "POLYCAB", lot: "125", type: "stock" },
  { name: "POWER FINANCE CORP", symbol: "PFC", lot: "1300", type: "stock" },
  { name: "POWER GRID CORP", symbol: "POWERGRID", lot: "1900", type: "stock" },
  { name: "PREMIER ENERGIES", symbol: "PREMIERENE", lot: "575", type: "stock" },
  { name: "PRESTIGE ESTATE", symbol: "PRESTIGE", lot: "450", type: "stock" },
  { name: "PUNJAB NATIONAL BANK", symbol: "PNB", lot: "8000", type: "stock" },
  { name: "RVNL", symbol: "RVNL", lot: "1525", type: "stock" },
  { name: "RBL BANK", symbol: "RBLBANK", lot: "3175", type: "stock" },
  { name: "REC LIMITED", symbol: "RECLTD", lot: "1400", type: "stock" },
  {
    name: "RELIANCE INDUSTRIES",
    symbol: "RELIANCE",
    lot: "500",
    type: "stock",
  },
  { name: "SAMMAAN CAPITAL", symbol: "SAMMAANCAP", lot: "4300", type: "stock" },
  {
    name: "SAMVRDHNA MOTHERSON",
    symbol: "MOTHERSON",
    lot: "6150",
    type: "stock",
  },
  { name: "SBI CARDS", symbol: "SBICARD", lot: "800", type: "stock" },
  { name: "SBI LIFE INSURANCE", symbol: "SBILIFE", lot: "375", type: "stock" },
  { name: "SHREE CEMENT", symbol: "SHREECEM", lot: "25", type: "stock" },
  { name: "SHRIRAM FINANCE", symbol: "SHRIRAMFIN", lot: "825", type: "stock" },
  { name: "SIEMENS", symbol: "SIEMENS", lot: "175", type: "stock" },
  { name: "SOLAR INDUSTRIES", symbol: "SOLARINDS", lot: "50", type: "stock" },
  {
    name: "SONA BLW PRECISION",
    symbol: "SONACOMS",
    lot: "1225",
    type: "stock",
  },
  { name: "SRF", symbol: "SRF", lot: "200", type: "stock" },
  { name: "STATE BANK OF INDIA", symbol: "SBIN", lot: "750", type: "stock" },
  { name: "SAIL", symbol: "SAIL", lot: "4700", type: "stock" },
  { name: "SUN PHARMA", symbol: "SUNPHARMA", lot: "350", type: "stock" },
  {
    name: "SUPREME INDUSTRIES",
    symbol: "SUPREMEIND",
    lot: "175",
    type: "stock",
  },
  { name: "SUZLON ENERGY", symbol: "SUZLON", lot: "9025", type: "stock" },
  { name: "SWIGGY", symbol: "SWIGGY", lot: "1300", type: "stock" },
  {
    name: "SYNGENE INTERNATIONAL",
    symbol: "SYNGENE",
    lot: "1000",
    type: "stock",
  },
  { name: "TCS", symbol: "TCS", lot: "175", type: "stock" },
  {
    name: "TATA CONSUMER PROD",
    symbol: "TATACONSUM",
    lot: "550",
    type: "stock",
  },
  { name: "TATA ELXSI", symbol: "TATAELXSI", lot: "100", type: "stock" },
  { name: "TATA MOTORS PV", symbol: "TMPV", lot: "800", type: "stock" },
  { name: "TATA POWER", symbol: "TATAPOWER", lot: "1450", type: "stock" },
  { name: "TATA STEEL", symbol: "TATASTEEL", lot: "5500", type: "stock" },
  { name: "TATA TECHNOLOGIES", symbol: "TATATECH", lot: "800", type: "stock" },
  { name: "TECH MAHINDRA", symbol: "TECHM", lot: "600", type: "stock" },
  {
    name: "INDIAN HOTELS (IHCL)",
    symbol: "INDHOTEL",
    lot: "1000",
    type: "stock",
  },
  { name: "PHOENIX MILLS", symbol: "PHOENIXLTD", lot: "350", type: "stock" },
  { name: "TITAN COMPANY", symbol: "TITAN", lot: "175", type: "stock" },
  { name: "TORRENT PHARMA", symbol: "TORNTPHARM", lot: "250", type: "stock" },
  { name: "TORRENT POWER", symbol: "TORNTPOWER", lot: "425", type: "stock" },
  { name: "TRENT", symbol: "TRENT", lot: "100", type: "stock" },
  { name: "TUBE INVESTMENTS", symbol: "TIINDIA", lot: "200", type: "stock" },
  { name: "TVS MOTOR", symbol: "TVSMOTOR", lot: "175", type: "stock" },
  { name: "ULTRATECH CEMENT", symbol: "ULTRACEMCO", lot: "50", type: "stock" },
  { name: "UNION BANK", symbol: "UNIONBANK", lot: "4425", type: "stock" },
  { name: "UNITED SPIRITS", symbol: "UNITDSPR", lot: "400", type: "stock" },
  { name: "UNO MINDA", symbol: "UNOMINDA", lot: "550", type: "stock" },
  { name: "UPL", symbol: "UPL", lot: "1355", type: "stock" },
  { name: "VARUN BEVERAGES", symbol: "VBL", lot: "1125", type: "stock" },
  { name: "VEDANTA", symbol: "VEDL", lot: "1150", type: "stock" },
  { name: "VODAFONE IDEA", symbol: "IDEA", lot: "71475", type: "stock" },
  { name: "VOLTAS", symbol: "VOLTAS", lot: "375", type: "stock" },
  { name: "WAAREE ENERGIES", symbol: "WAAREEENER", lot: "175", type: "stock" },
  { name: "WIPRO", symbol: "WIPRO", lot: "3000", type: "stock" },
  { name: "YES BANK", symbol: "YESBANK", lot: "31100", type: "stock" },
  {
    name: "ZYDUS LIFESCIENCES",
    symbol: "ZYDUSLIFE",
    lot: "900",
    type: "stock",
  },
];

export default FO_LIST;
