const watchlistArray = (companyId) => {
  return [
    {
      label: "JPPOWER",
      symbol: "JPPOWER",
      value: "INE351F01018",
      nse: true,
      bse: false,
      isActive: companyId === "INE351F01018",
      indexName: "NSE_EQ",
    },
    {
      label: "MAZDOCK",
      symbol: "MAZDOCK",
      value: "INE249Z01020",
      nse: true,
      bse: false,
      isActive: companyId === "INE249Z01020",
      indexName: "NSE_EQ",
    },
    {
      label: "NHPC",
      symbol: "NHPC",
      value: "INE848E01016",
      nse: true,
      bse: false,
      isActive: companyId === "INE848E01016",
      indexName: "NSE_EQ",
    },
    {
      label: "COALINDIA",
      symbol: "COALINDIA",
      value: "INE522F01014",
      nse: true,
      bse: false,
      isActive: companyId === "INE522F01014",
      indexName: "NSE_EQ",
    },
    {
      label: "IRFC",
      symbol: "IRFC",
      value: "INE053F01010",
      nse: true,
      bse: false,
      isActive: companyId === "INE053F01010",
      indexName: "NSE_EQ",
    },
    {
      label: "ONGC",
      symbol: "ONGC",
      value: "INE213A01029",
      nse: true,
      bse: false,
      isActive: companyId === "INE213A01029",
      indexName: "NSE_EQ",
    },
    {
      label: "RPOWER",
      symbol: "RPOWER",
      value: "INE614G01033",
      nse: true,
      bse: false,
      isActive: companyId === "INE614G01033",
      indexName: "NSE_EQ",
    },
    {
      label: "SUZLON",
      symbol: "SUZLON",
      value: "INE040H01021",
      nse: true,
      bse: false,
      isActive: companyId === "INE040H01021",
      indexName: "NSE_EQ",
    },
    {
      label: "SEPC",
      symbol: "SEPC",
      value: "INE964H01014",
      nse: true,
      bse: false,
      isActive: companyId === "INE964H01014",
      indexName: "NSE_EQ",
    },
    {
      label: "BPCL",
      symbol: "BPCL",
      value: "INE029A01011",
      nse: true,
      bse: false,
      isActive: companyId === "INE029A01011",
      indexName: "NSE_EQ",
    },
    {
      label: "GTLINFRA",
      symbol: "GTLINFRA",
      value: "INE221H01019",
      nse: true,
      bse: false,
      isActive: companyId === "INE221H01019",
      indexName: "NSE_EQ",
    },
    {
      label: "VEDANTA",
      symbol: "VEDL",
      value: "INE205A01025",
      nse: true,
      bse: false,
      isActive: companyId === "INE205A01025",
      indexName: "NSE_EQ",
    },
    {
      label: "BEL",
      symbol: "BEL",
      value: "INE263A01024",
      nse: true,
      bse: false,
      isActive: companyId === "INE263A01024",
      indexName: "NSE_EQ",
    },
    {
      label: "NBCC",
      symbol: "NBCC",
      value: "INE095N01031",
      nse: true,
      bse: false,
      isActive: companyId === "INE095N01031",
      indexName: "NSE_EQ",
    },
    {
      label: "SRESTHAFINVEST",
      symbol: "SRESTHA",
      value: "INE606K01049",
      nse: false,
      bse: true,
      isActive: companyId === "INE606K01049",
      indexName: "BSE_EQ",
    },
  ];
};

export default watchlistArray;
